# Generated by Django 3.2 on 2023-12-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('bday', models.DateField()),
                ('number', models.PositiveIntegerField(unique=True)),
                ('position', models.CharField(choices=[('QB', 'QB'), ('C', 'C'), ('G', 'G'), ('T', 'T'), ('RB', 'RB'), ('WR', 'WR'), ('TE', 'TE'), ('DT', 'DT'), ('DE', 'DE'), ('LB', 'LB'), ('CB', 'CB'), ('S', 'S'), ('Couch', 'Couch')], max_length=10)),
                ('team', models.CharField(choices=[('Amber Hawks', 'Amber Hawks'), ('Amber Kids', 'Amber Kids'), ('Amber Knight', 'Amber Knight'), ('women ff team', 'women ff team')], max_length=50)),
                ('inside_team', models.CharField(blank=True, choices=[('defence', 'defence'), ('offence', 'offence')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['number'],
            },
        ),
        migrations.AddConstraint(
            model_name='players',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'number', 'team'), name='unique_player'),
        ),
    ]
