# Generated by Django 4.0 on 2023-08-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('age', models.PositiveIntegerField()),
                ('bday', models.DateField()),
                ('number', models.PositiveIntegerField(unique=True)),
                ('position', models.CharField(choices=[('QB', 'QB'), ('C', 'C'), ('G', 'G'), ('T', 'T'), ('RB', 'RB'), ('WR', 'WR'), ('TE', 'TE'), ('DT', 'DT'), ('DE', 'DE'), ('LB', 'LB'), ('CB', 'CB'), ('S', 'S')], max_length=50)),
                ('team', models.CharField(choices=[('Amber Hawks', 'Янтарные Ястребы'), ('Amber Kids', 'Детская команда'), ('Amber Knight', 'Янтарный рыцарь'), ('women ff team', 'женская команда')], max_length=50)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['number'],
            },
        ),
    ]
