# Generated by Django 3.2 on 2023-12-25 11:10

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='bday',
            field=models.DateField(validators=[news.validators.validate_date]),
        ),
    ]
