# Generated by Django 3.2 on 2023-09-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.CharField(choices=[('QB', 'QB'), ('C', 'C'), ('G', 'G'), ('T', 'T'), ('RB', 'RB'), ('WR', 'WR'), ('TE', 'TE'), ('DT', 'DT'), ('DE', 'DE'), ('LB', 'LB'), ('CB', 'CB'), ('S', 'S')], max_length=10),
        ),
        migrations.AlterField(
            model_name='players',
            name='team',
            field=models.CharField(choices=[('Amber Hawks', 'Amber Hawks'), ('Amber Kids', 'Amber Kids'), ('Amber Knight', 'Amber Knight'), ('women ff team', 'women ff team')], max_length=50),
        ),
    ]
