# Generated by Django 3.2 on 2023-11-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_players_age'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='players',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'number'), name='unique_player'),
        ),
    ]
