# Generated by Django 3.2 on 2023-11-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_players_unique_player'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='players',
            name='unique_player',
        ),
        migrations.AlterField(
            model_name='players',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AddConstraint(
            model_name='players',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'number', 'team'), name='unique_player'),
        ),
    ]
