import localFont from 'next/font/local'
import 'src/app/globals.css'


const monsterrat = localFont({
  src: [
    {
      path: '../assets/fonts/Montserrat-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Montserrat-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-monsterrat'
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${monsterrat.variable}`}>{children}</body>
    </html>
  )
}
