# Generated by Django 3.2 on 2023-12-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
