# Generated by Django 3.2 on 2023-09-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='team',
            field=models.CharField(choices=[('Amber Hawks', 'Amber Hawks'), ('Amber Kids', 'Amber Kids'), ('Amber Knight', 'Amber Knight'), ('women ff team', 'women ff team')], max_length=50),
        ),
    ]
