# Generated by Django 3.2 on 2023-12-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'ПН'), ('1', 'ВТ'), ('2', 'СР'), ('3', 'ЧТ'), ('4', 'ПТ'), ('5', 'СБ'), ('6', 'ВС')], max_length=10, unique=True)),
                ('location', models.TextField(max_length=500)),
                ('time', models.TimeField(blank=True, null=True)),
                ('publeshed', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['day'],
            },
        ),
    ]
