# Generated by Django 3.2 on 2023-12-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='label',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назване'),
        ),
    ]
