# Generated by Django 3.2 on 2023-12-13 18:41

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='score',
            field=models.CharField(blank=True, default='- : -', max_length=16, null=True, validators=[news.validators.validate_colon]),
        ),
    ]
