# Generated by Django 3.2 on 2023-12-25 11:10

from django.db import migrations, models
import django.db.models.deletion
import news.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20231225_1310'),
        ('news', '0002_alter_games_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(validators=[news.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='games',
            name='date',
            field=models.DateField(validators=[news.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='games',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_team1', to='teams.teams', verbose_name='Хозяева'),
        ),
        migrations.AlterField(
            model_name='games',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_team2', to='teams.teams', verbose_name='Гости'),
        ),
    ]
