# Generated by Django 3.2 on 2023-11-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_games_depth_chart'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('title', 'text'), name='unique_news'),
        ),
    ]
